---
- name: Install a general virtual machine
  hosts: all
  vars_files:
    - config.yml
  remote_user: "{{ username }}"
  become: yes
  connection: local
  gather_facts: false
  
  tasks:
    - name: Wait for system to become reachable
      wait_for_connection:
        timeout: 300

    - name: Run apt update
      apt:
        update_cache: yes

    - name: Update all packages to their latest version
      apt:
        name: "*"
        state: latest

    - name: Install rclone
      apt:
        name: "rclone"
        state: latest
        
    - name: Install gedit
      apt:
        name: "gedit"
        state: present
   
    - name: Download Apptainer .deb package
      ansible.builtin.get_url:
        url: https://github.com/apptainer/apptainer/releases/download/v1.4.3/apptainer_1.4.3_amd64.deb
        dest: /home/{{ username }}/apptainer.deb
        mode: '0644'
        force: no

    - name: Install apptainer package
      ansible.builtin.apt:
        deb: /home/{{ username }}/apptainer.deb
        state: present
        
    - name: Create ~/Desktop/RD directory for mounting Research Drive
      ansible.builtin.file:
        path: "{{ root_path }}/Desktop/RD"
        state: directory
        mode: '0755'

        
