---
- name: Install a general virtual machine
  hosts: all
  # remote_user: barbera.vanschaik@mydre.org
  remote_user: bschaikvan
  become: yes
  connection: local
  gather_facts: false
  vars_files:
    - config.yml
  tasks:
    - name: Wait for system to become reachable
      wait_for_connection:
        timeout: 300

    - name: Run apt update
      apt:
        update_cache: yes

    - name: Update all packages to their latest version
      apt:
        name: "*"
        state: latest

    # - name: Install generic software
    #   apt:
    #     name:
    #     - apptainer

    - name: Add Conda repository
      ansible.builtin.shell: bash /home/{{ username }}/ansible/scripts/download-conda.sh
      args:
        executable: /bin/bash

    - name: Apt update after adding Conda repo
      apt:
        update_cache: yes

    - name: Install Conda
      apt:
        name: "conda"
        state: present

    - name: Add Conda to bashrc
      ansible.builtin.lineinfile:
        dest: /home/{{ username }}/.bashrc
        regexp: 'conda.sh'
        line: 'source /opt/conda/etc/profile.d/conda.sh'
        create: yes
        state: present

    - name: Activate conda in bashrc
      ansible.builtin.lineinfile:
        dest: /home/{{ username }}/.bashrc
        regexp: 'conda activate base'
        line: 'conda activate base'
        create: yes
        state: present

    - name: Download VScode .deb package
      ansible.builtin.get_url:
        url: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
        dest: /home/{{ username }}/vscode.deb
        mode: '0644'
        force: no

    - name: Install VScode .deb package
      ansible.builtin.apt:
        deb: /home/{{ username }}/vscode.deb
        state: present
