---
- name: Install a general virtual machine
  hosts: all
  remote_user: barbera.vanschaik@mydre.org
  become: yes
  connection: local
  gather_facts: false
  vars_files:
    - config.yml
  tasks:
    - name: Wait for system to become reachable
      wait_for_connection:
        timeout: 300

    - name: Run apt update
      apt:
        update_cache: yes

    - name: Update all packages to their latest version
      apt:
        name: "*"
        state: latest

    # - name: Install generic software
    #   apt:
    #     name:
    #     - apptainer

    - name: Add Conda repository
      ansible.builtin.shell: bash /home/{{ username }}/scripts/download-conda.sh
      args:
        executable: /bin/bash

    - name: Apt update after adding Conda repo
      apt:
        update_cache: yes

    - name: Install Conda
      apt:
        name: "conda"
        state: present

    - name: Add Conda to bashrc
      ansible.builtin.lineinfile:

    - name: Add Conda to bashrc
      ansible.builtin.lineinfile:
        dest: /home/{{ username }}/.bashrc
        regexp: 'conda.sh'
        line: 'source /opt/conda/etc/profile.d/conda.sh'
        create: yes
        state: present

    - name: Activate conda in bashrc
      ansible.builtin.lineinfile:
        dest: /home/{{ username }}/.bashrc
        regexp: 'conda activate base'
        line: 'conda activate base'
        create: yes
        state: present
        notify: Reload bashrc

