---
- name: Install R, Rstudio, Rtools, and example packages
  hosts: all
  vars_files:
    - config.yml
  remote_user: "{{ username }}"
  become: yes
  connection: local
  gather_facts: false
  
  tasks:
    - name: Install prerequisites for R
      ansible.builtin.package:
        name:
          - software-properties-common
          - dirmngr
          - wget
          - ca-certificates
          - gnupg2
          - apt-transport-https
          - curl
        state: present
        update_cache: yes

    - name: Remove old R GPG key if exists
      ansible.builtin.file:
        path: /usr/share/keyrings/r-project.gpg
        state: absent

    - name: Download R repository GPG key to temp file
      ansible.builtin.shell: |
        wget -e use_proxy=yes \
             -e http_proxy="{{ http_proxy }}" \
             -e https_proxy="{{ https_proxy }}" \
             -O /tmp/r-key.asc \
             https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc
      args:
        creates: /tmp/r-key.asc
      environment:
        http_proxy: "{{ http_proxy | default('') }}"
        https_proxy: "{{ https_proxy | default('') }}"
      register: wget_result

    - name: Verify key was downloaded
      ansible.builtin.stat:
        path: /tmp/r-key.asc
      register: key_file

    - name: Display download status
      ansible.builtin.debug:
        msg: "Key downloaded: {{ key_file.stat.exists }}, Size: {{ key_file.stat.size | default('N/A') }}"

    - name: Convert GPG key to binary format
      ansible.builtin.shell: |
        cat /tmp/r-key.asc | gpg --dearmor -o /usr/share/keyrings/r-project.gpg
        chmod 644 /usr/share/keyrings/r-project.gpg
      when: key_file.stat.exists
      register: gpg_result

    - name: Verify GPG key was created
      ansible.builtin.stat:
        path: /usr/share/keyrings/r-project.gpg
      register: gpg_key

    - name: Display GPG key status
      ansible.builtin.debug:
        msg: "GPG key created: {{ gpg_key.stat.exists }}, Size: {{ gpg_key.stat.size | default('N/A') }}"

    - name: Clean up temporary key file
      ansible.builtin.file:
        path: /tmp/r-key.asc
        state: absent

    - name: Get Ubuntu codename
      ansible.builtin.command:
        cmd: lsb_release -cs
      register: ubuntu_codename
      changed_when: false

    - name: Add R repository with signed-by
      ansible.builtin.copy:
        content: |
          deb [signed-by=/usr/share/keyrings/r-project.gpg] https://cloud.r-project.org/bin/linux/ubuntu {{ ubuntu_codename.stdout }}-cran40/
        dest: /etc/apt/sources.list.d/cran.list
        mode: '0644'
      when: gpg_key.stat.exists

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      environment:
        http_proxy: "{{ http_proxy | default('') }}"
        https_proxy: "{{ https_proxy | default('') }}"
      when: gpg_key.stat.exists

    - name: Install R base and development tools
      ansible.builtin.package:
        name:
          - r-base
          - r-base-dev
          - build-essential
          - libcurl4-openssl-dev
          - libssl-dev
          - libxml2-dev
          - libfontconfig1-dev
          - libharfbuzz-dev
          - libfribidi-dev
          - libfreetype6-dev
          - libpng-dev
          - libtiff5-dev
          - libjpeg-dev
        state: present

    - name: Check R version
      ansible.builtin.command:
        cmd: R --version
      register: r_version
      changed_when: false
      become: no

    - name: Display R version
      ansible.builtin.debug:
        msg: "{{ r_version.stdout_lines[0] }}"

    - name: Download RStudio
      ansible.builtin.get_url:
        url: https://download1.rstudio.org/electron/jammy/amd64/rstudio-2024.12.0-467-amd64.deb
        dest: /tmp/rstudio.deb
        mode: '0644'
      environment:
        http_proxy: "{{ http_proxy | default('') }}"
        https_proxy: "{{ https_proxy | default('') }}"

    - name: Install RStudio dependencies
      ansible.builtin.package:
        name:
          - libnss3
          - libnspr4
          - libgbm1
          - libasound2
        state: present

    - name: Install RStudio
      ansible.builtin.apt:
        deb: /tmp/rstudio.deb
        state: present

    - name: Clean up RStudio installer
      ansible.builtin.file:
        path: /tmp/rstudio.deb
        state: absent

    - name: Create R library directory for user
      ansible.builtin.file:
        path: "{{ root_path }}/R/library"
        state: directory
        mode: '0755'
      become: no

    - name: Configure R to use proxy (if needed)
      ansible.builtin.copy:
        content: |
          # R environment configuration
          {% if http_proxy is defined and http_proxy != '' %}
          options(
            repos = c(CRAN = "https://cloud.r-project.org/"),
            download.file.method = "libcurl",
            HTTPUserAgent = sprintf("R/%s R (%s)", getRversion(), paste(getRversion(), R.version$platform, R.version$arch, R.version$os))
          )
          
          # Proxy settings
          Sys.setenv(
            http_proxy = "{{ http_proxy }}",
            https_proxy = "{{ https_proxy }}",
            HTTP_PROXY = "{{ http_proxy }}",
            HTTPS_PROXY = "{{ https_proxy }}"
          )
          {% else %}
          options(
            repos = c(CRAN = "https://cloud.r-project.org/"),
            download.file.method = "libcurl"
          )
          {% endif %}
          
          # Set library path
          .libPaths(c("{{ root_path }}/R/library", .libPaths()))
          
          message("✓ R environment configured")
        dest: "{{ root_path }}/.Rprofile"
        mode: '0644'
      become: no

    - name: Install R packages (renv and ggplot2)
      ansible.builtin.shell: |
        R -e 'install.packages(c("renv", "ggplot2"), lib="{{ root_path }}/R/library", repos="https://cloud.r-project.org/")'
      become: no
      environment:
        HOME: "{{ root_path }}"
        R_LIBS_USER: "{{ root_path }}/R/library"
        http_proxy: "{{ http_proxy | default('') }}"
        https_proxy: "{{ https_proxy | default('') }}"
      register: r_packages_install
      failed_when: false

    - name: Display R package installation output
      ansible.builtin.debug:
        var: r_packages_install.stdout_lines
      when: r_packages_install.stdout_lines is defined

    - name: Verify R packages installation
      ansible.builtin.shell: |
        R -e 'library(renv); library(ggplot2); cat("✓ Packages loaded successfully\n")'
      become: no
      environment:
        HOME: "{{ root_path }}"
        R_LIBS_USER: "{{ root_path }}/R/library"
      register: r_verify
      failed_when: false

    - name: Display verification result
      ansible.builtin.debug:
        msg: "{{ r_verify.stdout if r_verify.rc == 0 else 'Package installation may have failed - check logs' }}"

    - name: Display installation summary
      ansible.builtin.debug:
        msg: |
          ✓ R installation complete
          ✓ RStudio installed
          ✓ R packages: renv, ggplot2
          
          To use:
          - R command line: type 'R' in terminal
          - RStudio: search for RStudio in applications menu
          
          R library location: {{ root_path }}/R/library
          R configuration: {{ root_path }}/.Rprofile