---
- name: Install and configure XEmacs on Ubuntu
  hosts: all
  become: yes
  vars:
    xemacs_packages_dir: "/usr/local/share/xemacs/site-packages"
    xemacs_user_dir: "{{ ansible_env.HOME }}/.xemacs"
    
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install XEmacs and dependencies
      apt:
        name:
          - xemacs21
          - xemacs21-bin
          - xemacs21-support
          - xemacs21-basesupport
        state: present

    - name: Create XEmacs user directory
      file:
        path: "{{ xemacs_user_dir }}"
        state: directory
        mode: '0755'
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
      become: no

    - name: Download YAML mode from GNU
      get_url:
        url: "https://github.com/yoshiki/yaml-mode/raw/master/yaml-mode.el"
        dest: "{{ xemacs_user_dir }}/yaml-mode.el"
        mode: '0644'
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
      become: no

    - name: Download Markdown mode
      get_url:
        url: "https://jblevins.org/projects/markdown-mode/markdown-mode.el"
        dest: "{{ xemacs_user_dir }}/markdown-mode.el"
        mode: '0644'
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
      become: no

    - name: Download Python mode
      get_url:
        url: "https://gitlab.com/groups/python-mode-devs/-/raw/master/python-mode.el"
        dest: "{{ xemacs_user_dir }}/python-mode.el"
        mode: '0644'
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
      become: no
      ignore_errors: yes

    - name: Download MATLAB mode
      get_url:
        url: "https://git.code.sf.net/p/matlab-emacs/src/ci/master/tree/matlab.el?format=raw"
        dest: "{{ xemacs_user_dir }}/matlab.el"
        mode: '0644'
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
      become: no
      ignore_errors: yes

    - name: Create XEmacs init file with configuration
      copy:
        dest: "{{ xemacs_user_dir }}/init.el"
        mode: '0644'
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
        content: |
          ;;; XEmacs init.el - Custom configuration
          ;;; Generated by Ansible
          
          ;; Set load path for custom packages
          (add-to-list 'load-path "{{ xemacs_user_dir }}")
          
          ;; ========================================
          ;; Visual Configuration
          ;; ========================================
          
          ;; Set white background
          (set-face-background 'default "white")
          (set-face-foreground 'default "black")
          
          ;; Set decent fonts
          (set-face-font 'default "-*-Liberation Mono-normal-normal-normal-*-14-*-*-*-m-0-iso10646-1")
          
          ;; Disable startup message
          (setq inhibit-startup-message t)
          
          ;; Show line numbers
          (setq line-number-mode t)
          (setq column-number-mode t)
          
          ;; Enable syntax highlighting
          (global-font-lock-mode t)
          (setq font-lock-maximum-decoration t)
          
          ;; Better scrolling
          (setq scroll-step 1)
          (setq scroll-conservatively 10000)
          
          ;; Show matching parentheses
          (show-paren-mode t)
          (setq show-paren-style 'mixed)
          
          ;; ========================================
          ;; General Editor Settings
          ;; ========================================
          
          ;; Use spaces instead of tabs
          (setq-default indent-tabs-mode nil)
          (setq-default tab-width 4)
          
          ;; Auto-save and backup settings
          (setq make-backup-files t)
          (setq backup-directory-alist '(("." . "~/.xemacs/backups")))
          
          ;; Enable auto-revert for files changed on disk
          (global-auto-revert-mode t)
          
          ;; ========================================
          ;; YAML Mode Configuration
          ;; ========================================
          
          (require 'yaml-mode nil t)
          (when (featurep 'yaml-mode)
            (add-to-list 'auto-mode-alist '("\\.yml\\'" . yaml-mode))
            (add-to-list 'auto-mode-alist '("\\.yaml\\'" . yaml-mode))
            (add-hook 'yaml-mode-hook
                      '(lambda ()
                         (define-key yaml-mode-map "\C-m" 'newline-and-indent))))
          
          ;; ========================================
          ;; Markdown Mode Configuration
          ;; ========================================
          
          (require 'markdown-mode nil t)
          (when (featurep 'markdown-mode)
            (add-to-list 'auto-mode-alist '("\\.md\\'" . markdown-mode))
            (add-to-list 'auto-mode-alist '("\\.markdown\\'" . markdown-mode))
            (add-hook 'markdown-mode-hook
                      '(lambda ()
                         (visual-line-mode t)
                         (setq fill-column 80))))
          
          ;; ========================================
          ;; Python Mode Configuration
          ;; ========================================
          
          (require 'python-mode nil t)
          (when (featurep 'python-mode)
            (add-to-list 'auto-mode-alist '("\\.py\\'" . python-mode))
            (add-hook 'python-mode-hook
                      '(lambda ()
                         (setq python-indent-offset 4)
                         (setq indent-tabs-mode nil))))
          
          ;; ========================================
          ;; MATLAB Mode Configuration
          ;; ========================================
          
          (require 'matlab nil t)
          (when (featurep 'matlab)
            (add-to-list 'auto-mode-alist '("\\.m\\'" . matlab-mode))
            (add-hook 'matlab-mode-hook
                      '(lambda ()
                         (setq matlab-indent-level 4)
                         (setq fill-column 76))))
          
          ;; ========================================
          ;; Additional Conveniences
          ;; ========================================
          
          ;; Recent files
          (require 'recentf nil t)
          (when (featurep 'recentf)
            (recentf-mode 1)
            (setq recentf-max-menu-items 25))
          
          ;; Better buffer switching
          (iswitchb-mode t)
          
          ;; Enable mouse support in terminal
          (unless window-system
            (xterm-mouse-mode t))
          
          ;; Custom key bindings
          (global-set-key (kbd "C-x C-b") 'buffer-menu)
          
          ;; Message on successful load
          (message "XEmacs configuration loaded successfully!")
      become: no

    - name: Create backups directory
      file:
        path: "{{ xemacs_user_dir }}/backups"
        state: directory
        mode: '0755'
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
      become: no

    - name: Create custom.el file for user customizations
      copy:
        dest: "{{ xemacs_user_dir }}/custom.el"
        mode: '0644'
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
        content: |
          ;;; custom.el - User-specific customizations
          ;;; Add your personal customizations here
          
          ;; This file is loaded by init.el
        force: no
      become: no

    - name: Verify XEmacs installation
      command: xemacs --version
      register: xemacs_version
      changed_when: false

    - name: Display XEmacs version
      debug:
        msg: "XEmacs installed: {{ xemacs_version.stdout_lines[0] }}"